import { useState } from 'react';
import {
  MessageSquareHeart,
  Trophy,
  AlertCircle,
  Moon,
  TrendingUp,
  Share2,
  Check,
  Compass,
  Camera
} from 'lucide-react';
import { StateOfYouReport } from '../../types';
import { LongitudinalMemoryHub } from './LongitudinalMemoryHub';
import { ShareableStoryCardModal } from '../common/ShareableStoryCardModal';

interface StateOfYouViewProps {
  report: StateOfYouReport | null;
  loading: boolean;
  userId?: number;
}

export const StateOfYouView: React.FC<StateOfYouViewProps> = ({ report, loading, userId = 1 }) => {
  const [copied, setCopied] = useState(false);
  const [showStoryModal, setShowStoryModal] = useState<boolean>(false);

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto py-12 px-4 space-y-4 animate-pulse">
        <div className="h-44 bg-slate-900/60 rounded-3xl border border-slate-800"></div>
        <div className="h-64 bg-slate-900/60 rounded-3xl border border-slate-800"></div>
      </div>
    );
  }

  if (!report) return null;

  const handleShare = () => {
    navigator.clipboard.writeText(`${report.coach_letter}\n\n— Generated by Sahay AI Negotiator (sahay.app)`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <span className="text-xs uppercase font-bold tracking-wider px-2.5 py-0.5 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/30">
              Weekly Synthesis
            </span>
            <span className="text-xs text-slate-400 font-mono">• {report.report_period}</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight mt-1.5">
            The "State of You" Reflection
          </h2>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Written by your AI ally based on your actual compliance and energy data this week.
          </p>
        </div>

        <div className="flex items-center gap-2.5 self-start">
          <button
            onClick={() => setShowStoryModal(true)}
            className="flex items-center space-x-2 px-4 py-2.5 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white rounded-xl text-xs sm:text-sm font-bold shadow-lg shadow-emerald-950/40 transition-all active:scale-95"
          >
            <Camera className="w-4 h-4" />
            <span>📸 Story Card / WhatsApp</span>
          </button>
          <button
            onClick={handleShare}
            className="flex items-center space-x-2 px-3.5 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs sm:text-sm font-bold border border-slate-700 transition-all active:scale-95"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Share2 className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
        </div>
      </div>

      {/* Main Coach Letter Card */}
      <div className="bg-gradient-to-br from-indigo-950/60 via-slate-900 to-purple-950/40 border border-indigo-500/40 rounded-3xl p-6 sm:p-8 shadow-2xl space-y-5 relative overflow-hidden">
        <div className="flex items-center space-x-3 border-b border-slate-800/80 pb-4">
          <div className="w-10 h-10 rounded-2xl bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center text-indigo-300">
            <MessageSquareHeart className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-extrabold text-base text-white">Coach's Reflection Note</h3>
            <p className="text-xs text-slate-400">Personalized weekly analysis</p>
          </div>
        </div>

        <p className="text-sm sm:text-base text-slate-100 font-medium leading-relaxed italic sm:px-2">
          "{report.coach_letter}"
        </p>

        {/* 4 Analytical Pillars */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 pt-4">
          <div className="bg-navy-950/80 border border-slate-800 rounded-2xl p-4 flex items-start space-x-3">
            <div className="w-8 h-8 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shrink-0 mt-0.5">
              <Trophy className="w-4 h-4" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400">
                Top Win This Week
              </span>
              <p className="text-xs text-slate-200 mt-0.5 leading-snug">{report.top_win}</p>
            </div>
          </div>

          <div className="bg-navy-950/80 border border-slate-800 rounded-2xl p-4 flex items-start space-x-3">
            <div className="w-8 h-8 rounded-xl bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0 mt-0.5">
              <AlertCircle className="w-4 h-4" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-amber-400">
                Friction Pattern to Solve
              </span>
              <p className="text-xs text-slate-200 mt-0.5 leading-snug">{report.friction_pattern}</p>
            </div>
          </div>

          <div className="bg-navy-950/80 border border-slate-800 rounded-2xl p-4 flex items-start space-x-3">
            <div className="w-8 h-8 rounded-xl bg-teal-500/15 border border-teal-500/30 flex items-center justify-center text-teal-400 shrink-0 mt-0.5">
              <Moon className="w-4 h-4" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-teal-400">
                Circadian & Sleep Sync
              </span>
              <p className="text-xs text-slate-200 mt-0.5 leading-snug">{report.sleep_health_note}</p>
            </div>
          </div>

          <div className="bg-navy-950/80 border border-slate-800 rounded-2xl p-4 flex items-start space-x-3">
            <div className="w-8 h-8 rounded-xl bg-purple-500/15 border border-purple-500/30 flex items-center justify-center text-purple-400 shrink-0 mt-0.5">
              <TrendingUp className="w-4 h-4" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-purple-400">
                Exam Pacing
              </span>
              <p className="text-xs text-slate-200 mt-0.5 leading-snug">{report.readiness_summary}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Recommended Strategy for Next Week */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex items-start space-x-3.5">
        <div className="w-9 h-9 rounded-xl bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center text-indigo-300 shrink-0 mt-0.5">
          <Compass className="w-5 h-5" />
        </div>
        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-indigo-300">
            Next Week's Gameplan
          </h4>
          <p className="text-sm font-semibold text-white mt-1">
            {report.recommended_focus_next_week}
          </p>
        </div>
      </div>

      {/* Moat Pillar 2 & 4: Compounding Longitudinal Memory & Failure Forensics Breakdown */}
      <LongitudinalMemoryHub userId={userId} />

      {/* Viral Shareable Story Card Modal */}
      <ShareableStoryCardModal
        isOpen={showStoryModal}
        onClose={() => setShowStoryModal(false)}
        report={report}
      />
    </div>
  );
};
